Update epg.yml

diff --git a/.github/workflows/epg.yml b/.github/workflows/epg.yml
--- a/.github/workflows/epg.yml
+++ b/.github/workflows/epg.yml
@@ -29,12 +29,15 @@ jobs:
       run: |
         python getEpgs.py
 
-    - name: Commit and push changes
+    - name: Commit changes if needed for epg.xml
       run: |
-        git config --global user.name "github-actions[bot]"
-        git config --global user.email "github-actions[bot]@users.noreply.github.com"
+        git config user.name "github-actions"
+        git config user.email "github-actions@github.com"
         git add epg.xml
-        git commit -m "EPG Updated! 📺"
-        git push
-      env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        changes=$(git diff --cached --stat)
+        if [ -n "$changes" ]; then
+          if echo "$changes" | grep -q "epg.xml"; then
+            git commit -m "EPG Updated! 📺"
+            git push || echo "Push failed due to permissions or no changes."
+          fi
+        fi
